[general]
# Deixa em tela cheia
fullscreen = true

# Encerra o programa após copiar ou salvar a imagem
early-exit = true

# Arredonda as bordas das formas
corner-roundness = 2

# Pré define uma ferramenta ao inicializar [pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "crop"

# Comando que vai ser executado ao copiar (CTRL+C)
copy-command = "wl-copy"

# Ao copiar a imagem, ela também será salva
save-after-copy = true

# Acão ao apertar Esc (Escape) [save-to-clipboard, save-to-file, exit]
actions-on-escape = ["exit"]

[color-palette]
# Paleta de cores para as ferramentas
palette = [
    "#ffffff", # branco
    "#000000", # preto
    "#ff0000", # vermelho
    "#00ff00", # verde
    "#0000ff", # azul
    "#4F86F7", # blueberry (Cor destaque do sistema)
]

[keybinds]
# Teclas de atalho para as ferramentas
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "z"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "g"

[font]
# Fonte que vai ser utilizada
family = "CaskaydiaCove Nerd Font"
style = "Regular"

# # Hide toolbars by default
# default-hide-toolbars = true
# # Experimental (since 0.20.0): whether window focus shows/hides toolbars. This does not affect initial state of toolbars, see default-hide-toolbars.
# focus-toggles-toolbars = false
# # Fill shapes by default (since 0.20.0)
# default-fill-shapes = false
# # The primary highlighter to use, the other is accessible by holding CTRL at the start of a highlight [possible values: block, freehand]
# primary-highlighter = "block"
# # Disable notifications
# disable-notifications = false
# # Actions to trigger on right click (order is important)
# # [possible values: save-to-clipboard, save-to-file, exit]
# actions-on-right-click = []
# # Actions to trigger on Enter key (order is important)
# # [possible values: save-to-clipboard, save-to-file, exit]
# actions-on-enter = ["save-to-clipboard"]
# # Action to perform when the Enter key is pressed [possible values: save-to-clipboard, save-to-file]
# # Deprecated: use actions-on-enter instead
# action-on-enter = "save-to-clipboard"
# # Right click to copy
# # Deprecated: use actions-on-right-click instead
# right-click-copy = false
# # request no window decoration. Please note that the compositor has the final say in this. At this point. requires xdg-decoration-unstable-v1.
# no-window-decoration = true
# # experimental feature: adjust history size for brush input smooting (0: disabled, default: 0, try e.g. 5 or 10)
# brush-smooth-history-size = 10
# # experimental feature (NEXTRELEASE): The pan step size to use when panning with arrow keys.
# pan-step-size = 50.0
# # experimental feature (NEXTRELEASE): The zoom factor to use for the image.
# # 1.0 means no zooming.
# zoom-factor = 1.1
#



#
# # These will be available in the color picker as presets
# # Leave empty to use GTK's default
# custom = [
#     "#00ffff",
#     "#a52a2a",
#     "#dc143c",
#     "#ff1493",
#     "#ffd700",
#     "#008000",
# ]